# Generated by Django 4.1.5 on 2023-01-25 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala_Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Sala_Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('es_administrador', models.BooleanField()),
                ('id_sala_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.sala_chat')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mensaje', models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 8, 46, 31429))),
                ('mensaje', models.CharField(max_length=2000)),
                ('id_user_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user_sala_chat')),
            ],
        ),
    ]
