# Generated by Django 4.1.5 on 2023-01-25 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_mensajes_fecha_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 26, 4, 970511)),
        ),
        migrations.AlterField(
            model_name='sala_chat',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 26, 4, 970511)),
        ),
        migrations.AlterField(
            model_name='user_sala_chat',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 26, 4, 970511)),
        ),
    ]
