# Generated by Django 4.1.5 on 2023-01-26 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_mensajes_fecha_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala_chat',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 6, 24, 10, 673283)),
        ),
        migrations.AlterField(
            model_name='user_sala_chat',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 6, 24, 10, 673283)),
        ),
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
