# Generated by Django 4.1.5 on 2023-01-26 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_sala_chat_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala_chat',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 6, 24, 31, 467237)),
        ),
        migrations.AlterField(
            model_name='user_sala_chat',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 6, 24, 31, 467237)),
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mensaje', models.DateTimeField(default=datetime.datetime(2023, 1, 26, 6, 24, 31, 467237))),
                ('mensaje', models.CharField(max_length=2000)),
                ('id_sala_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.sala_chat')),
                ('id_user_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user_sala_chat')),
            ],
        ),
    ]
